### ISSUE TITLE
Python version line seems to be unformatted when called in JupyterNB

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/pyansys-tools-report#18]
Reported by @plule-ansys, the Python Version line seems to have an incorrect output when formatted into table:

![image](https://user-images.githubusercontent.com/37798125/173782663-7bd550f7-1970-472e-81e3-1d0132f4d66c.png)

We should look into the reason for this output...

**Comment by RobPasMue** [comment]
Reading through the scooby.Report class (a package which we inherit and use for this output), it looks like it's the way they implement it. There is not much to control about it, apart from opening an issue on their repo. If it's critical for Ansys, I'll work on this. Otherwise, I suggest to "live with it".

@plule-ansys do you agree? The link to the scooby.Report class is here https://github.com/banesullivan/scooby/blob/main/scooby/report.py

**Comment by RobPasMue** [comment]
@plule-ansys could you provide some feedback when possible? =) Otherwise I'll proceed to close the issue.

**Comment by plule-ansys** [comment]
@RobPasMue hey sorry I missed your previous ping. This is definitely not critical in any way, at best cosmetic. Thank you for looking into it, I'm closing the issue!

**Comment by RobPasMue** [comment]
No problem! I guessed you were on holidays =) Thanks @plule-ansys
