### ISSUE TITLE
Some libraries are not detected

### ISSUE THREAD

**Issue by germa89** [pyansys/pyansys-tools-report#59]
It seems some libraries are not correctly detected.

```text
Core packages
-------------
ansys.mapdl.core    : 0.64.dev0
numpy               : 1.23.5
appdirs             : 1.4.4
scipy               : 1.9.3
grpc                : Package not found
ansys.api.mapdl.v0  : Package not found
ansys.mapdl.reader  : 0.52.4
google.protobuf     : Package not found
pexpect             : 4.8.0
```

Link: https://github.com/pyansys/pymapdl/actions/runs/3733984882/jobs/6335972283#step:7:151

**Comment by RobPasMue** [comment]
Let me check into this whenever I have time @germa89 :)

**Comment by RobPasMue** [comment]
Starting to work on this... (if nothing comes up in the meantime)

**Comment by RobPasMue** [comment]
Also, adding additional deps: 

![image](https://user-images.githubusercontent.com/37798125/210245833-3555ae93-9c50-4300-ab1f-8dca05f71395.png)
